export interface EssentialWord {
  id: string;
  en: string;
  pt: string;
  phonetic: string;
  category: string;
  sprint: number;
}

// Helper to create word objects
const createWord = (id: string, en: string, pt: string, cat: string, phonetic: string = '') => ({
  id, en, pt, phonetic, category: cat
});

const RAW_POOL = [
  // PRONOMES
  createWord('p1', 'I', 'eu', 'Pronomes', 'ai'),
  createWord('p2', 'You', 'você/vocês', 'Pronomes', 'iu'),
  createWord('p3', 'He', 'ele', 'Pronomes', 'ri'),
  createWord('p4', 'She', 'ela', 'Pronomes', 'chi'),
  createWord('p5', 'It', 'ele/ela (coisas/animais)', 'Pronomes', 'it'),
  createWord('p6', 'We', 'nós', 'Pronomes', 'ui'),
  createWord('p7', 'They', 'eles/elas', 'Pronomes', 'dei'),
  createWord('p8', 'My', 'meu/minha', 'Pronomes', 'mai'),
  createWord('p9', 'Your', 'seu/sua', 'Pronomes', 'iór'),
  createWord('p10', 'His', 'dele', 'Pronomes', 'riz'),
  createWord('p11', 'Her', 'dela', 'Pronomes', 'rãr'),
  createWord('p12', 'Its', 'dele/dela (coisas/animais)', 'Pronomes', 'its'),
  createWord('p13', 'Our', 'nosso/nossa', 'Pronomes', 'au-ar'),
  createWord('p14', 'Their', 'deles/delas', 'Pronomes', 'dé-ar'),

  // ARTIGOS
  createWord('a1', 'A', 'um/uma (antes de consoante)', 'Artigos', 'êi'),
  createWord('a2', 'An', 'um/uma (antes de vogal)', 'Artigos', 'én'),
  createWord('a3', 'The', 'o/a/os/as', 'Artigos', 'dã'),
  createWord('a4', 'This', 'este/esta', 'Artigos', 'dis'),
  createWord('a5', 'That', 'aquele/aquela', 'Artigos', 'dét'),
  createWord('a6', 'These', 'estes/estas', 'Artigos', 'diiz'),
  createWord('a7', 'Those', 'aqueles/aquelas', 'Artigos', 'douz'),

  // VERBOS
  createWord('v1', 'To be', 'ser/estar', 'Verbos', 'tu bi'),
  createWord('v2', 'To have', 'ter', 'Verbos', 'tu rév'),
  createWord('v3', 'To do', 'fazer', 'Verbos', 'tu du'),
  createWord('v4', 'To say', 'dizer', 'Verbos', 'tu sei'),
  createWord('v5', 'To go', 'ir', 'Verbos', 'tu gou'),
  createWord('v6', 'To make', 'fazer/criar', 'Verbos', 'tu meik'),
  createWord('v7', 'To know', 'saber/conhecer', 'Verbos', 'tu nou'),
  createWord('v8', 'To think', 'pensar', 'Verbos', 'tu dink'),
  createWord('v9', 'To take', 'pegar/levar', 'Verbos', 'tu teik'),
  createWord('v10', 'To see', 'ver', 'Verbos', 'tu sii'),
  createWord('v11', 'To come', 'vir', 'Verbos', 'tu câm'),
  createWord('v12', 'To want', 'querer', 'Verbos', 'tu uónt'),
  createWord('v13', 'To look', 'olhar', 'Verbos', 'tu luuk'),
  createWord('v14', 'To use', 'usar', 'Verbos', 'tu iuz'),
  createWord('v15', 'To find', 'encontrar', 'Verbos', 'tu faind'),
  createWord('v16', 'To give', 'dar', 'Verbos', 'tu guiv'),
  createWord('v17', 'To tell', 'contar/dizer', 'Verbos', 'tu tél'),
  createWord('v18', 'To work', 'trabalhar', 'Verbos', 'tu uórk'),
  createWord('v19', 'To call', 'chamar/ligar', 'Verbos', 'tu cól'),
  createWord('v20', 'To feel', 'sentir', 'Verbos', 'tu fii-ol'),
  createWord('v21', 'To ask', 'perguntar/pedir', 'Verbos', 'tu é-sk'),
  createWord('v22', 'To try', 'tentar/experimentar', 'Verbos', 'tu trai'),
  createWord('v23', 'To leave', 'deixar/sair', 'Verbos', 'tu liiv'),
  createWord('v24', 'To need', 'precisar', 'Verbos', 'tu niid'),
  createWord('v25', 'To get', 'obter/chegar/receber', 'Verbos', 'tu guét'),
  createWord('v26', 'To put', 'colocar', 'Verbos', 'tu puut'),
  createWord('v27', 'To read', 'ler', 'Verbos', 'tu riid'),
  createWord('v28', 'To write', 'escrever', 'Verbos', 'tu rait'),
  createWord('v29', 'To speak', 'falar', 'Verbos', 'tu spiik'),
  createWord('v30', 'To hear', 'ouvir', 'Verbos', 'tu rí-ar'),
  createWord('v31', 'To play', 'jogar/brincar/tocar', 'Verbos', 'tu plei'),
  createWord('v32', 'To run', 'correr', 'Verbos', 'tu rân'),
  createWord('v33', 'To walk', 'caminhar', 'Verbos', 'tu uók'),
  createWord('v34', 'To eat', 'comer', 'Verbos', 'tu iit'),
  createWord('v35', 'To drink', 'beber', 'Verbos', 'tu drink'),
  createWord('v36', 'To sleep', 'dormir', 'Verbos', 'tu sliip'),
  createWord('v37', 'To study', 'estudar', 'Verbos', 'tu istã-di'),
  createWord('v38', 'To teach', 'ensinar', 'Verbos', 'tu tiitch'),
  createWord('v39', 'To learn', 'aprender', 'Verbos', 'tu lêrn'),
  createWord('v40', 'To meet', 'encontrar/conhecer', 'Verbos', 'tu miit'),
  createWord('v41', 'To start', 'começar', 'Verbos', 'tu start'),
  createWord('v42', 'To stop', 'parar', 'Verbos', 'tu istóp'),
  createWord('v43', 'To open', 'abrir', 'Verbos', 'tu ou-pên'),
  createWord('v44', 'To close', 'fechar', 'Verbos', 'tu clouz'),
  createWord('v45', 'To live', 'viver/morar', 'Verbos', 'tu liv'),
  createWord('v46', 'To die', 'morrer', 'Verbos', 'tu dai'),
  createWord('v47', 'To bring', 'trazer', 'Verbos', 'tu bring'),
  createWord('v48', 'To send', 'enviar', 'Verbos', 'tu sénd'),
  createWord('v49', 'To wait', 'esperar', 'Verbos', 'tu ueit'),
  createWord('v50', 'To buy', 'comprar', 'Verbos', 'tu bai'),
  createWord('v51', 'To sell', 'vender', 'Verbos', 'tu sél'),
  createWord('v52', 'To pay', 'pagar', 'Verbos', 'tu pei'),
  createWord('v53', 'To cook', 'cozinhar', 'Verbos', 'tu cuuk'),
  createWord('v54', 'To wash', 'lavar', 'Verbos', 'tu uóch'),
  createWord('v55', 'To cut', 'cortar', 'Verbos', 'tu cât'),
  createWord('v56', 'To grow', 'crescer/cultivar', 'Verbos', 'tu grou'),
  createWord('v57', 'To win', 'vencer/ganhar', 'Verbos', 'tu uin'),
  createWord('v58', 'To lose', 'perder', 'Verbos', 'tu luz'),
  createWord('v59', 'To build', 'construir', 'Verbos', 'tu bi-old'),
  createWord('v60', 'To break', 'quebrar', 'Verbos', 'tu breik'),
  createWord('v61', 'To catch', 'pegar/capturar', 'Verbos', 'tu kétch'),
  createWord('v62', 'To throw', 'jogar/arremessar', 'Verbos', 'tu drou'),
  createWord('v63', 'To fall', 'cair', 'Verbos', 'tu fól'),
  createWord('v64', 'To push', 'empurrar', 'Verbos', 'tu puch'),
  createWord('v65', 'To pull', 'puxar', 'Verbos', 'tu pul'),
  createWord('v66', 'To drive', 'dirigir', 'Verbos', 'tu draiv'),
  createWord('v67', 'To ride', 'andar de (bicicleta/moto)', 'Verbos', 'tu raid'),
  createWord('v68', 'To sing', 'cantar', 'Verbos', 'tu sing'),
  createWord('v69', 'To dance', 'dançar', 'Verbos', 'tu dé-nss'),
  createWord('v70', 'To draw', 'desenhar', 'Verbos', 'tu dró'),
  createWord('v71', 'To paint', 'pintar', 'Verbos', 'tu peint'),
  createWord('v72', 'To laugh', 'rir', 'Verbos', 'tu lé-f'),
  createWord('v73', 'To cry', 'chorar', 'Verbos', 'tu crai'),
  createWord('v74', 'To show', 'mostrar', 'Verbos', 'tu chou'),
  createWord('v75', 'To hold', 'segurar', 'Verbos', 'tu rô-old'),
  createWord('v76', 'To keep', 'manter/guardar', 'Verbos', 'tu kiip'),
  createWord('v77', 'To let', 'deixar/permitir', 'Verbos', 'tu lét'),
  createWord('v78', 'To allow', 'permitir', 'Verbos', 'tu a-lau'),
  createWord('v79', 'To mean', 'significar', 'Verbos', 'tu miin'),
  createWord('v80', 'To agree', 'concordar', 'Verbos', 'tu a-grii'),
  createWord('v81', 'To believe', 'acreditar', 'Verbos', 'tu bi-liiv'),
  createWord('v82', 'To hope', 'esperar (ter esperança)', 'Verbos', 'tu roup'),
  createWord('v83', 'To wish', 'desejar', 'Verbos', 'tu uich'),
  createWord('v84', 'To plan', 'planejar', 'Verbos', 'tu plén'),
  createWord('v85', 'To decide', 'decidir', 'Verbos', 'tu di-said'),
  createWord('v86', 'To remember', 'lembrar', 'Verbos', 'tu ri-mém-ber'),
  createWord('v87', 'To forget', 'esquecer', 'Verbos', 'tu for-guét'),
  createWord('v88', 'To explain', 'explicar', 'Verbos', 'tu éks-plein'),
  createWord('v89', 'To describe', 'descrever', 'Verbos', 'tu di-scraib'),
  createWord('v90', 'To understand', 'entender', 'Verbos', 'tu ân-der-isténd'),

  // PREPOSIÇÕES
  createWord('pr1', 'In', 'em/dentro de', 'Preposições', 'in'),
  createWord('pr2', 'On', 'em/sobre', 'Preposições', 'on'),
  createWord('pr3', 'At', 'em/às', 'Preposições', 'ét'),
  createWord('pr4', 'Of', 'de', 'Preposições', 'óv'),
  createWord('pr5', 'To', 'para/a', 'Preposições', 'tu'),
  createWord('pr6', 'For', 'para/por', 'Preposições', 'fór'),
  createWord('pr7', 'With', 'com', 'Preposições', 'wid'),
  createWord('pr8', 'From', 'de/origem', 'Preposições', 'fróm'),
  createWord('pr9', 'By', 'por/perto de', 'Preposições', 'bai'),
  createWord('pr10', 'About', 'sobre/a respeito de', 'Preposições', 'a-bau-t'),
  createWord('pr11', 'Into', 'para dentro de', 'Preposições', 'in-tu'),

  // ADVÉRBIOS
  createWord('adv1', 'And', 'e', 'Adv/Conj', 'énd'),
  createWord('adv2', 'But', 'mas', 'Adv/Conj', 'bât'),
  createWord('adv3', 'Or', 'ou', 'Adv/Conj', 'ór'),
  createWord('adv4', 'So', 'então/assim', 'Adv/Conj', 'sou'),
  createWord('adv5', 'Because', 'porque', 'Adv/Conj', 'bi-cóz'),
  createWord('adv6', 'Very', 'muito', 'Adv/Conj', 'vé-ri'),
  createWord('adv7', 'Now', 'agora', 'Adv/Conj', 'nau'),
  createWord('adv8', 'Then', 'então/depois', 'Adv/Conj', 'dén'),
  createWord('adv9', 'Here', 'aqui', 'Adv/Conj', 'rí-ar'),
  createWord('adv10', 'There', 'lá', 'Adv/Conj', 'dé-ar'),
  createWord('adv11', 'Also', 'também', 'Adv/Conj', 'ól-sou'),
  createWord('adv12', 'Always', 'sempre', 'Adv/Conj', 'ól-ueiz'),
  createWord('adv13', 'Never', 'nunca', 'Adv/Conj', 'né-ver'),
  createWord('adv14', 'Often', 'frequentemente', 'Adv/Conj', 'ó-fên'),
  createWord('adv15', 'Sometimes', 'às vezes', 'Adv/Conj', 'sâm-taimz'),
  createWord('adv16', 'Just', 'apenas/só', 'Adv/Conj', 'djâst'),
  createWord('adv17', 'Even', 'até mesmo', 'Adv/Conj', 'ii-vên'),
  createWord('adv18', 'Away', 'longe/para fora', 'Adv/Conj', 'a-uei'),
  createWord('adv19', 'Back', 'de volta/atrás', 'Adv/Conj', 'bék'),
  createWord('adv20', 'Down', 'para baixo', 'Adv/Conj', 'daun'),
  createWord('adv21', 'Up', 'para cima', 'Adv/Conj', 'âp'),
  createWord('adv22', 'Inside', 'dentro', 'Adv/Conj', 'in-said'),
  createWord('adv23', 'Outside', 'fora', 'Adv/Conj', 'aut-said'),
  createWord('adv24', 'Ago', 'atrás (tempo)', 'Adv/Conj', 'a-gou'),
  createWord('adv25', 'Still', 'ainda', 'Adv/Conj', 'is-til'),
  createWord('adv26', 'Yet', 'ainda (negativo/pergunta)', 'Adv/Conj', 'iét'),
  createWord('adv27', 'Already', 'já', 'Adv/Conj', 'ól-ré-di'),
  createWord('adv28', 'However', 'no entanto', 'Adv/Conj', 'rau-é-ver'),
  createWord('adv29', 'Although', 'embora', 'Adv/Conj', 'ól-dou'),
  createWord('adv30', 'While', 'enquanto', 'Adv/Conj', 'uail'),
  createWord('adv31', 'Until', 'até', 'Adv/Conj', 'ân-til'),
  createWord('adv32', 'Early', 'cedo', 'Adv/Conj', 'êr-li'),
  createWord('adv33', 'Late', 'tarde', 'Adv/Conj', 'leit'),
  createWord('adv34', 'Slowly', 'lentamente', 'Adv/Conj', 'slou-li'),
  createWord('adv35', 'Usually', 'geralmente', 'Adv/Conj', 'iú-ju-a-li'),
  createWord('adv36', 'Rarely', 'raramente', 'Adv/Conj', 'rér-li'),
  createWord('adv37', 'Every', 'cada/todo', 'Adv/Conj', 'é-vri'),

  // ADJETIVOS
  createWord('adj1', 'Good', 'bom/boa', 'Adjetivos', 'guud'),
  createWord('adj2', 'Bad', 'mau/má', 'Adjetivos', 'béd'),
  createWord('adj3', 'New', 'novo/nova', 'Adjetivos', 'niu'),
  createWord('adj4', 'Old', 'velho/velha', 'Adjetivos', 'ould'),
  createWord('adj5', 'Big', 'grande', 'Adjetivos', 'big'),
  createWord('adj6', 'Small', 'pequeno/pequena', 'Adjetivos', 'is-mól'),
  createWord('adj7', 'Happy', 'feliz', 'Adjetivos', 'ré-pi'),
  createWord('adj8', 'Sad', 'triste', 'Adjetivos', 'séd'),
  createWord('adj9', 'Hot', 'quente', 'Adjetivos', 'rót'),
  createWord('adj10', 'Cold', 'frio/fria', 'Adjetivos', 'could'),
  createWord('adj11', 'Long', 'longo/comprido', 'Adjetivos', 'lóng'),
  createWord('adj12', 'Short', 'curto/baixo', 'Adjetivos', 'chór-t'),
  createWord('adj13', 'High', 'alto', 'Adjetivos', 'rai'),
  createWord('adj14', 'Low', 'baixo', 'Adjetivos', 'lou'),
  createWord('adj15', 'Right', 'certo/direita', 'Adjetivos', 'rait'),
  createWord('adj16', 'Left', 'esquerdo/esquerda', 'Adjetivos', 'lé-ft'),
  createWord('adj17', 'True', 'verdadeiro', 'Adjetivos', 'truu'),
  createWord('adj18', 'False', 'falso', 'Adjetivos', 'fól-ss'),
  createWord('adj19', 'Fast', 'rápido/a', 'Adjetivos', 'fást'),
  createWord('adj20', 'Slow', 'lento/a', 'Adjetivos', 'slou'),
  createWord('adj21', 'Easy', 'fácil', 'Adjetivos', 'ii-zi'),
  createWord('adj22', 'Hard/Difficult', 'difícil/duro', 'Adjetivos', 'rard / di-fi-câlt'),
  createWord('adj23', 'Clean', 'limpo/a', 'Adjetivos', 'cliin'),
  createWord('adj24', 'Dirty', 'sujo/a', 'Adjetivos', 'dêr-ti'),
  createWord('adj25', 'Full', 'cheio/a', 'Adjetivos', 'ful'),
  createWord('adj26', 'Empty', 'vazio/a', 'Adjetivos', 'émp-ti'),
  createWord('adj27', 'Light', 'leve/claro', 'Adjetivos', 'lait'),
  createWord('adj28', 'Dark', 'escuro/a', 'Adjetivos', 'dárk'),
  createWord('adj29', 'Rich', 'rico/a', 'Adjetivos', 'ritch'),
  createWord('adj30', 'Poor', 'pobre', 'Adjetivos', 'pu-ar'),
  createWord('adj31', 'Free', 'livre/grátis', 'Adjetivos', 'frii'),
  createWord('adj32', 'Busy', 'ocupado/a', 'Adjetivos', 'bi-zi'),
  createWord('adj33', 'Important', 'importante', 'Adjetivos', 'im-pór-tânt'),
  createWord('adj34', 'Different', 'diferente', 'Adjetivos', 'di-fê-rênt'),
  createWord('adj35', 'Same', 'mesmo/a', 'Adjetivos', 'seim'),
  createWord('adj36', 'Young', 'jovem', 'Adjetivos', 'iâng'),
  createWord('adj37', 'Beautiful', 'bonito/a', 'Adjetivos', 'biú-ti-ful'),
  createWord('adj38', 'Ugly', 'feio/a', 'Adjetivos', 'â-gli'),
  createWord('adj39', 'Nice', 'agradável/legal', 'Adjetivos', 'naiss'),
  createWord('adj40', 'Kind', 'gentil', 'Adjetivos', 'kaind'),
  createWord('adj41', 'Angry', 'com raiva', 'Adjetivos', 'én-gri'),
  createWord('adj42', 'Scared', 'com medo', 'Adjetivos', 'is-kérd'),
  createWord('adj43', 'Excited', 'animado/a', 'Adjetivos', 'ek-sai-têd'),
  createWord('adj44', 'Tired', 'cansado/a', 'Adjetivos', 'tai-erd'),
  createWord('adj45', 'Hungry', 'com fome', 'Adjetivos', 'rân-gri'),
  createWord('adj46', 'Thirsty', 'com sede', 'Adjetivos', 'dêrs-ti'),
  createWord('adj47', 'Expensive', 'caro/a', 'Adjetivos', 'eks-pén-ssiv'),
  createWord('adj48', 'Cheap', 'barato/a', 'Adjetivos', 'tchiip'),
  createWord('adj49', 'Warm', 'morno/quente', 'Adjetivos', 'uórm'),
  createWord('adj50', 'Cool', 'fresco/legal', 'Adjetivos', 'cuul'),
  createWord('adj51', 'Wet', 'molhado/a', 'Adjetivos', 'uét'),
  createWord('adj52', 'Dry', 'seco/a', 'Adjetivos', 'drai'),
  createWord('adj53', 'Funny', 'engraçado/a', 'Adjetivos', 'fâ-ni'),
  createWord('adj54', 'Awful/Terrible', 'terrível', 'Adjetivos', 'ó-ful / té-ri-bol'),
  createWord('adj55', 'Great', 'ótimo/a', 'Adjetivos', 'greit'),
  createWord('adj56', 'Excellent', 'excelente', 'Adjetivos', 'ék-sse-lent'),
  createWord('adj57', 'Wonderful', 'maravilhoso/a', 'Adjetivos', 'uân-der-ful'),
  createWord('adj58', 'Boring', 'chato/a', 'Adjetivos', 'bó-rin'),
  createWord('adj59', 'Interesting', 'interessante', 'Adjetivos', 'in-tre-stin'),
  createWord('adj60', 'Quiet', 'silencioso/a', 'Adjetivos', 'cuai-et'),
  createWord('adj61', 'Loud', 'barulhento/a', 'Adjetivos', 'lau-d'),
  createWord('adj62', 'Bright', 'brilhante', 'Adjetivos', 'brait'),
  createWord('adj63', 'Strong', 'forte', 'Adjetivos', 'istróng'),
  createWord('adj64', 'Weak', 'fraco/a', 'Adjetivos', 'uiik'),
  createWord('adj65', 'Heavy', 'pesado/a', 'Adjetivos', 'ré-vi'),
  createWord('adj66', 'Soft', 'macio/a', 'Adjetivos', 'só-ft'),
  createWord('adj67', 'Ready', 'pronto/a', 'Adjetivos', 'ré-di'),
  createWord('adj68', 'Sure', 'certo/a', 'Adjetivos', 'chur'),
  createWord('adj69', 'Possible', 'possível', 'Adjetivos', 'pó-ssi-bol'),
  createWord('adj70', 'Impossible', 'impossível', 'Adjetivos', 'im-pó-ssi-bol'),
  createWord('adj71', 'Serious', 'sério/a', 'Adjetivos', 'sí-ri-as'),

  // SUBSTANTIVOS
  createWord('n1', 'Time', 'tempo/hora', 'Substantivos', 'taim'),
  createWord('n2', 'Man', 'homem', 'Substantivos', 'mén'),
  createWord('n3', 'Woman', 'mulher', 'Substantivos', 'uú-man'),
  createWord('n4', 'Child', 'criança', 'Substantivos', 'tchai-old'),
  createWord('n5', 'Person', 'pessoa', 'Substantivos', 'pêr-son'),
  createWord('n6', 'Family', 'família', 'Substantivos', 'fé-mi-li'),
  createWord('n7', 'Friend', 'amigo/a', 'Substantivos', 'frénd'),
  createWord('n8', 'Home/House', 'casa/lar', 'Substantivos', 'roum / rauss'),
  createWord('n9', 'City', 'cidade', 'Substantivos', 'sí-ti'),
  createWord('n10', 'Country', 'país/campo', 'Substantivos', 'cân-tri'),
  createWord('n11', 'World', 'mundo', 'Substantivos', 'uôr-ld'),
  createWord('n12', 'Day', 'dia', 'Substantivos', 'dei'),
  createWord('n13', 'Night', 'noite', 'Substantivos', 'nait'),
  createWord('n14', 'Morning', 'manhã', 'Substantivos', 'mór-nin'),
  createWord('n15', 'Afternoon', 'tarde', 'Substantivos', 'áf-ter-nuun'),
  createWord('n16', 'Evening', 'noite (começo)', 'Substantivos', 'ii-v-nin'),
  createWord('n17', 'Week', 'semana', 'Substantivos', 'uiik'),
  createWord('n18', 'Month', 'mês', 'Substantivos', 'mânth'),
  createWord('n19', 'Year', 'ano', 'Substantivos', 'í-ar'),
  createWord('n20', 'Thing', 'coisa', 'Substantivos', 'dink'),
  createWord('n21', 'Money', 'dinheiro', 'Substantivos', 'mâ-ni'),
  createWord('n22', 'Water', 'água', 'Substantivos', 'uó-ter'),
  createWord('n23', 'Food', 'comida', 'Substantivos', 'fuud'),
  createWord('n24', 'Car', 'carro', 'Substantivos', 'cár'),
  createWord('n25', 'Book', 'livro', 'Substantivos', 'buuk'),
  createWord('n26', 'Table', 'mesa', 'Substantivos', 'tei-bol'),
  createWord('n27', 'Chair', 'cadeira', 'Substantivos', 'tché-ar'),
  createWord('n28', 'Door', 'porta', 'Substantivos', 'dór'),
  createWord('n29', 'Window', 'janela', 'Substantivos', 'uín-dou'),
  createWord('n30', 'Bed', 'cama', 'Substantivos', 'béd'),
  createWord('n31', 'Room', 'quarto/cômodo', 'Substantivos', 'ruum'),
  createWord('n32', 'Work', 'trabalho', 'Substantivos', 'uôrk'),
  createWord('n33', 'School', 'escola', 'Substantivos', 'is-cuul'),
  createWord('n34', 'Job', 'emprego', 'Substantivos', 'djob'),
  createWord('n35', 'Store/Shop', 'loja', 'Substantivos', 'is-tór / chóp'),
  createWord('n36', 'Hospital', 'hospital', 'Substantivos', 'rós-pi-tol'),
  createWord('n37', 'Bank', 'banco', 'Substantivos', 'bénk'),
  createWord('n38', 'Airport', 'aeroporto', 'Substantivos', 'ér-pórt'),
  createWord('n39', 'Station', 'estação', 'Substantivos', 'is-tei-chon'),
  createWord('n40', 'Street', 'rua', 'Substantivos', 'is-triit'),
  createWord('n41', 'Road', 'estrada', 'Substantivos', 'roud'),
  createWord('n42', 'Garden', 'jardim', 'Substantivos', 'gár-den'),
  createWord('n43', 'Park', 'parque', 'Substantivos', 'párk'),
  createWord('n44', 'Beach', 'praia', 'Substantivos', 'bi-itch'),
  createWord('n45', 'Mountain', 'montanha', 'Substantivos', 'máun-ten'),
  createWord('n46', 'River', 'rio', 'Substantivos', 'rí-ver'),
  createWord('n47', 'Ocean/Sea', 'oceano/mar', 'Substantivos', 'ó-chon / sii'),
  createWord('n48', 'Air', 'ar', 'Substantivos', 'ér'),
  createWord('n49', 'Fire', 'fogo', 'Substantivos', 'fai-er'),
  createWord('n50', 'Sun', 'sol', 'Substantivos', 'sân'),
  createWord('n51', 'Moon', 'lua', 'Substantivos', 'muun'),
  createWord('n52', 'Star', 'estrela', 'Substantivos', 'is-tár'),
  createWord('n53', 'Weather', 'clima/tempo', 'Substantivos', 'ué-der'),
  createWord('n54', 'Problem', 'problema', 'Substantivos', 'pró-blem'),
  createWord('n55', 'Solution', 'solução', 'Substantivos', 'so-lú-chon'),
  createWord('n56', 'Idea', 'ideia', 'Substantivos', 'ai-dí-a'),
  createWord('n57', 'Question', 'pergunta', 'Substantivos', 'cués-tchon'),
  createWord('n58', 'Answer', 'resposta', 'Substantivos', 'én-sser'),
  createWord('n59', 'Number', 'número', 'Substantivos', 'nâm-ber'),
  createWord('n60', 'Part', 'parte', 'Substantivos', 'párt'),
  createWord('n61', 'Side', 'lado', 'Substantivos', 'said'),
  createWord('n62', 'Parent', 'pai/mãe', 'Substantivos', 'pé-rent'),
  createWord('n63', 'Brother', 'irmão', 'Substantivos', 'bró-der'),
  createWord('n64', 'Sister', 'irmã', 'Substantivos', 'sís-ter'),
  createWord('n65', 'Son', 'filho', 'Substantivos', 'sân'),
  createWord('n66', 'Daughter', 'filha', 'Substantivos', 'dó-ter'),
  createWord('n67', 'Husband', 'marido', 'Substantivos', 'râs-bând'),
  createWord('n68', 'Wife', 'esposa', 'Substantivos', 'uaif'),
  createWord('n69', 'Teacher', 'professor/a', 'Substantivos', 'ti-tcher'),
  createWord('n70', 'Student', 'estudante', 'Substantivos', 'is-tú-dent'),
  createWord('n71', 'Doctor', 'médico/a', 'Substantivos', 'dóc-tor'),
  createWord('n72', 'Police', 'polícia', 'Substantivos', 'po-liiss'),
  createWord('n73', 'Boss', 'chefe', 'Substantivos', 'bóss'),
  createWord('n74', 'Customer', 'cliente', 'Substantivos', 'câs-to-mer'),
  createWord('n75', 'Neighbor', 'vizinho/a', 'Substantivos', 'nei-bor'),
  createWord('n76', 'Stranger', 'estranho/a', 'Substantivos', 'is-trein-djer'),
  createWord('n77', 'Boy', 'menino', 'Substantivos', 'bói'),
  createWord('n78', 'Girl', 'menina', 'Substantivos', 'guêrl'),
  createWord('n79', 'Opinion', 'opinião', 'Substantivos', 'o-pi-nion'),
  createWord('n80', 'Fact', 'fato', 'Substantivos', 'fé-kt'),
  createWord('n81', 'Truth', 'verdade', 'Substantivos', 'truuth'),
  createWord('n82', 'Lie', 'mentira', 'Substantivos', 'lai'),
  createWord('n83', 'Reason', 'razão/motivo', 'Substantivos', 'ri-zon'),
  createWord('n84', 'Cause', 'causa', 'Substantivos', 'cóz'),
  createWord('n85', 'Effect', 'efeito', 'Substantivos', 'i-fé-kt'),
  createWord('n86', 'Meaning', 'significado', 'Substantivos', 'mii-nin'),
  createWord('n87', 'Difference', 'diferença', 'Substantivos', 'di-fê-rêns'),
  createWord('n88', 'Similarity', 'similaridade', 'Substantivos', 'si-mi-lá-ri-ti'),
  createWord('n89', 'Choice', 'escolha', 'Substantivos', 'tchoiss'),
  createWord('n90', 'Decision', 'decisão', 'Substantivos', 'di-ssi-jion'),
  createWord('n91', 'Luck', 'sorte', 'Substantivos', 'lâk'),
  createWord('n92', 'Chance', 'chance/acaso', 'Substantivos', 'tchén-ss'),
  createWord('n93', 'Experience', 'experiência', 'Substantivos', 'ek-spi-ri-êns'),
  createWord('n94', 'Knowledge', 'conhecimento', 'Substantivos', 'nó-lêdj'),
  createWord('n95', 'Skill', 'habilidade', 'Substantivos', 'is-ki-ol'),
  createWord('n96', 'Talent', 'talento', 'Substantivos', 'té-lent'),
  createWord('n97', 'Effort', 'esforço', 'Substantivos', 'é-fórt'),

  // ÚTEIS
  createWord('ut1', 'Yes', 'sim', 'Úteis', 'iéss'),
  createWord('ut2', 'No', 'não', 'Úteis', 'nou'),
  createWord('ut3', 'Please', 'por favor', 'Úteis', 'pliiz'),
  createWord('ut4', 'Thank you', 'obrigado/a', 'Úteis', 'ténk-iu'),
  createWord('ut5', 'Excuse me', 'com licença/desculpe', 'Úteis', 'eks-kiuz mi'),
  createWord('ut6', 'Sorry', 'desculpe', 'Úteis', 'só-ri'),
  createWord('ut7', 'Hello', 'olá', 'Úteis', 're-lou'),
  createWord('ut8', 'Goodbye', 'adeus', 'Úteis', 'guud-bai'),
  createWord('ut9', 'May', 'poder (permissão)', 'Úteis', 'mei'),
  createWord('ut10', 'Can', 'poder (capacidade)', 'Úteis', 'kén'),
  createWord('ut11', 'Must', 'dever/precisar', 'Úteis', 'mâst'),
  createWord('ut12', 'Should', 'deveria', 'Úteis', 'chuud'),
  createWord('ut13', 'Could', 'poderia', 'Úteis', 'cuud'),
  createWord('ut14', 'Will', 'irá (futuro)', 'Úteis', 'uil'),
  createWord('ut15', 'Would', 'iria (condicional)', 'Úteis', 'uudd'),
  createWord('ut16', 'Like', 'gostar/como', 'Úteis', 'laik'),
  createWord('ut17', 'Much', 'muito (incontáveis)', 'Úteis', 'mâtch'),
  createWord('ut18', 'Many', 'muitos (contáveis)', 'Úteis', 'mé-ni'),
  createWord('ut19', 'Little', 'pouco (incontáveis)', 'Úteis', 'li-tol'),
  createWord('ut20', 'Few', 'poucos (contáveis)', 'Úteis', 'fiu'),
  createWord('ut21', 'More', 'mais', 'Úteis', 'mór'),
  createWord('ut22', 'Less', 'menos', 'Úteis', 'léss'),
  createWord('ut23', 'Most', 'a maioria', 'Úteis', 'moust'),
  createWord('ut24', 'Least', 'o menos', 'Úteis', 'liist'),
  createWord('ut25', 'Enough', 'suficiente', 'Úteis', 'i-nâf'),
  createWord('ut26', 'Quickly', 'rapidamente', 'Úteis', 'cuic-kli'),
  createWord('ut27', 'Carefully', 'cuidadosamente', 'Úteis', 'kér-fu-li'),
  createWord('ut28', 'Easily', 'facilmente', 'Úteis', 'ii-zi-li'),
  createWord('ut29', 'Happily', 'felizmente', 'Úteis', 'ré-pi-li'),
  createWord('ut30', 'Sadly', 'tristemente', 'Úteis', 'séd-li'),
  createWord('ut31', 'Really', 'realmente', 'Úteis', 'rí-li'),
  createWord('ut32', 'Finally', 'finalmente', 'Úteis', 'fai-na-li'),
  createWord('ut33', 'Exactly', 'exatamente', 'Úteis', 'eg-zét-li'),
  createWord('ut34', 'Almost', 'quase', 'Úteis', 'ól-moust'),
  createWord('ut35', 'Immediately', 'imediatamente', 'Úteis', 'i-mi-di-et-li'),
  createWord('ut36', 'Eventually', 'finalmente', 'Úteis', 'i-vén-tchu-a-li'),
  createWord('ut37', 'Currently', 'atualmente', 'Úteis', 'câ-rent-li'),
  createWord('ut38', 'Recently', 'recentemente', 'Úteis', 'ri-ssent-li'),
  createWord('ut39', 'Previously', 'anteriormente', 'Úteis', 'pri-vi-ous-li'),

  // TECNOLOGIA
  createWord('tc1', 'Internet', 'internet', 'Tecnologia', 'in-ter-nét'),
  createWord('tc2', 'Email', 'e-mail', 'Tecnologia', 'i-meil'),
  createWord('tc3', 'Message', 'mensagem', 'Tecnologia', 'mé-ssedj'),
  createWord('tc4', 'Website', 'website', 'Tecnologia', 'uéb-sait'),
  createWord('tc5', 'App', 'aplicativo', 'Tecnologia', 'ép'),
  createWord('tc6', 'Camera', 'câmera', 'Tecnologia', 'ké-me-ra'),
  createWord('tc7', 'Photo', 'foto', 'Tecnologia', 'fó-tou'),
  createWord('tc8', 'Video', 'vídeo', 'Tecnologia', 'ví-di-ou'),
  createWord('tc9', 'Music', 'música', 'Tecnologia', 'miú-zik'),
  createWord('tc10', 'News', 'notícias', 'Tecnologia', 'niuz'),
  createWord('tc11', 'Radio', 'rádio', 'Tecnologia', 'rei-di-ou'),
  createWord('tc12', 'TV', 'televisão', 'Tecnologia', 'ti-vi'),
  createWord('tc13', 'Movie/Film', 'filme', 'Tecnologia', 'mú-vi / film'),
  createWord('tc14', 'Letter', 'carta/letra', 'Tecnologia', 'lé-ter'),
  createWord('tc15', 'Word', 'palavra', 'Tecnologia', 'uórd'),
  createWord('tc16', 'Language', 'idioma', 'Tecnologia', 'léng-uê-dj'),

  // DIREÇÕES
  createWord('d1', 'North', 'norte', 'Direções', 'nórth'),
  createWord('d2', 'South', 'sul', 'Direções', 'sauth'),
  createWord('d3', 'East', 'leste', 'Direções', 'iist'),
  createWord('d4', 'West', 'oeste', 'Direções', 'uést'),
  createWord('d5', 'Straight', 'reto/em frente', 'Direções', 'streit'),
  createWord('d6', 'Near', 'perto', 'Direções', 'ní-ar'),
  createWord('d7', 'Far', 'longe', 'Direções', 'fár'),
  createWord('d8', 'Above', 'acima de', 'Direções', 'a-bâv'),
  createWord('d9', 'Below/Under', 'abaixo de', 'Direções', 'bi-lou / ân-der'),
  createWord('d10', 'Front', 'frente', 'Direções', 'frânt'),
  createWord('d11', 'Middle', 'meio', 'Direções', 'mi-dol'),
  createWord('d12', 'Corner', 'esquina/canto', 'Direções', 'cór-ner'),
  createWord('d13', 'Center', 'centro', 'Direções', 'sên-ter'),

  // CRIME
  createWord('cr1', 'Crime', 'crime', 'Séries', 'craim'),
  createWord('cr2', 'Mystery', 'mistério', 'Séries', 'mís-te-ri'),
  createWord('cr3', 'Evidence', 'evidência', 'Séries', 'é-vi-dêns'),
  createWord('cr4', 'Suspect', 'suspeito', 'Séries', 'sâs-pékt'),
  createWord('cr5', 'Victim', 'vítima', 'Séries', 'víc-tim'),
  createWord('cr6', 'Detective', 'detetive', 'Séries', 'di-téc-tiv'),
  createWord('cr7', 'Case', 'caso', 'Séries', 'keiss'),
  createWord('cr8', 'Clue', 'pista', 'Séries', 'cluu'),
  createWord('cr9', 'Witness', 'testemunha', 'Séries', 'uít-nês'),
  createWord('cr10', 'Alibi', 'álibi', 'Séries', 'á-li-bai'),
  createWord('cr11', 'Motive', 'motivo', 'Séries', 'mó-tiv'),
  createWord('cr12', 'Investigation', 'investigação', 'Séries', 'in-vé-sti-guei-chon'),
  createWord('cr13', 'Arrest', 'prender', 'Séries', 'a-rést'),
  createWord('cr14', 'Trial', 'julgamento', 'Séries', 'trai-ol'),
  createWord('cr15', 'Lawyer', 'advogado/a', 'Séries', 'lói-er'),
  createWord('cr16', 'Judge', 'juiz/juíza', 'Séries', 'djudj'),
  createWord('cr17', 'Court', 'tribunal', 'Séries', 'córt'),
  createWord('cr18', 'Guilty', 'culpado/a', 'Séries', 'guil-ti'),
  createWord('cr19', 'Innocent', 'inocente', 'Séries', 'í-no-ssent'),

  // RELAÇÕES
  createWord('rel1', 'Friendship', 'amizade', 'Relações', 'frénd-chip'),
  createWord('rel2', 'Relationship', 'relacionamento', 'Relações', 'ri-lei-chon-chip'),
  createWord('rel3', 'Love', 'amor', 'Relações', 'lâv'),
  createWord('rel4', 'Life', 'vida', 'Relações', 'laif'),
  createWord('rel5', 'Feeling', 'sentimento', 'Relações', 'fii-lin'),
  createWord('rel6', 'Talk', 'conversar/falar', 'Relações', 'tók'),
  createWord('rel7', 'Listen', 'ouvir', 'Relações', 'li-ssên'),
  createWord('rel8', 'Help', 'ajudar', 'Relações', 'rélp'),

  // NATUREZA
  createWord('nt1', 'Tree', 'árvore', 'Natureza', 'trii'),
  createWord('nt2', 'Flower', 'flor', 'Natureza', 'flau-er'),
  createWord('nt3', 'Grass', 'grama', 'Natureza', 'gráss'),
  createWord('nt4', 'Forest', 'floresta', 'Natureza', 'fó-rést'),
  createWord('nt5', 'Lake', 'lago', 'Natureza', 'leik'),
  createWord('nt6', 'Sky', 'céu', 'Natureza', 'is-kai'),
  createWord('nt7', 'Cloud', 'nuvem', 'Natureza', 'claud'),
  createWord('nt8', 'Rain', 'chuva', 'Natureza', 'rein'),
  createWord('nt9', 'Snow', 'neve', 'Natureza', 'is-nou'),
  createWord('nt10', 'Wind', 'vento', 'Natureza', 'uind'),
  createWord('nt11', 'Animal', 'animal', 'Natureza', 'á-ni-mol'),
  createWord('nt12', 'Bird', 'pássaro', 'Natureza', 'bêrd'),
  createWord('nt13', 'Fish', 'peixe', 'Natureza', 'fich'),
  createWord('nt14', 'Insect', 'inseto', 'Natureza', 'in-ssékt'),
  createWord('nt15', 'Plant', 'planta', 'Natureza', 'plént'),

  // SAÚDE
  createWord('hl1', 'Body', 'corpo', 'Saúde', 'bó-di'),
  createWord('hl2', 'Head', 'cabeça', 'Saúde', 'rédd'),
  createWord('hl3', 'Hand', 'mão', 'Saúde', 'rénd'),
  createWord('hl4', 'Foot', 'pé', 'Saúde', 'fuut'),
  createWord('hl5', 'Arm', 'braço', 'Saúde', 'árm'),
  createWord('hl6', 'Leg', 'perna', 'Saúde', 'lég'),
  createWord('hl7', 'Eye', 'olho', 'Saúde', 'ai'),
  createWord('hl8', 'Ear', 'orelha', 'Saúde', 'í-ar'),
  createWord('hl9', 'Nose', 'nariz', 'Saúde', 'nouz'),
  createWord('hl10', 'Mouth', 'boca', 'Saúde', 'mauth'),
  createWord('hl11', 'Tooth', 'dente', 'Saúde', 'tuuth'),
  createWord('hl12', 'Hair', 'cabelo', 'Saúde', 'ré-ar'),
  createWord('hl13', 'Health', 'saúde', 'Saúde', 'rélth'),
  createWord('hl14', 'Sick', 'doente', 'Saúde', 'ssík'),
  createWord('hl15', 'Well', 'bem/saudável', 'Saúde', 'uél'),
  createWord('hl16', 'Pain', 'dor', 'Saúde', 'pein'),
  createWord('hl17', 'Medicine', 'remédio', 'Saúde', 'mé-di-ssin'),
  createWord('hl18', 'Nurse', 'enfermeiro/a', 'Saúde', 'nêr-ss'),

  // VIAGEM
  createWord('tr1', 'Plane', 'avião', 'Viagem', 'plein'),
  createWord('tr2', 'Flight', 'voo', 'Viagem', 'flait'),
  createWord('tr3', 'Ticket', 'passagem', 'Viagem', 'tí-kêt'),
  createWord('tr4', 'Passport', 'passaporte', 'Viagem', 'pás-port'),
  createWord('tr5', 'Suitcase/Luggage', 'mala/bagagem', 'Viagem', 'suut-keiss / lâ-guê-dj'),
  createWord('tr6', 'Train', 'trem', 'Viagem', 'trein'),
  createWord('tr7', 'Bus', 'ônibus', 'Viagem', 'bâss'),
  createWord('tr8', 'Taxi', 'táxi', 'Viagem', 'ték-ssi'),
  createWord('tr9', 'Subway/Metro', 'metrô', 'Viagem', 'sâb-uei / mé-trou'),
  createWord('tr10', 'Route', 'rota', 'Viagem', 'ruut'),
  createWord('tr11', 'Map', 'mapa', 'Viagem', 'mép'),
  createWord('tr12', 'Direction', 'direção', 'Viagem', 'di-rék-chon'),
  createWord('tr13', 'Traffic', 'trânsito', 'Viagem', 'tré-fic'),
  createWord('tr14', 'Journey/Trip', 'viagem', 'Viagem', 'djêr-ni / tríp'),
  createWord('tr15', 'Destination', 'destino', 'Viagem', 'dés-ti-nei-chon'),
  createWord('tr16', 'Departure', 'partida', 'Viagem', 'di-pár-tchur'),
  createWord('tr17', 'Arrival', 'chegada', 'Viagem', 'a-rai-vol'),

  // TRABALHO
  createWord('wk1', 'Branch', 'filial', 'Trabalho', 'bréntch'),
  createWord('wk2', 'Office', 'escritório', 'Trabalho', 'ó-fiice'),
  createWord('wk3', 'Meeting', 'reunião', 'Trabalho', 'mii-tin'),
  createWord('wk4', 'Company', 'empresa', 'Trabalho', 'câm-pa-ni'),
  createWord('wk5', 'Employee', 'funcionário/a', 'Trabalho', 'em-ploi-ii'),
  createWord('wk6', 'Manager', 'gerente', 'Trabalho', 'mé-na-djer'),
  createWord('wk7', 'Project', 'projeto', 'Trabalho', 'pró-djekt'),
  createWord('wk8', 'Goal', 'meta/objetivo', 'Trabalho', 'goul'),
  createWord('wk9', 'Product', 'produto', 'Trabalho', 'pró-dâkt'),
  createWord('wk10', 'Service', 'serviço', 'Trabalho', 'sêr-viice'),
  createWord('wk11', 'Market', 'mercado', 'Trabalho', 'már-kêt'),
  createWord('wk12', 'Price', 'preço', 'Trabalho', 'praiss'),
  createWord('wk13', 'Cost', 'custo', 'Trabalho', 'cóst'),
  createWord('wk14', 'Profit', 'lucro', 'Trabalho', 'pró-fit'),
  createWord('wk15', 'Loss', 'prejuízo', 'Trabalho', 'lóss'),
  createWord('wk16', 'Economy', 'economia', 'Trabalho', 'i-có-no-mi'),

  // CORES
  createWord('col1', 'Red', 'vermelho', 'Cores', 'réd'),
  createWord('col2', 'Blue', 'azul', 'Cores', 'bluu'),
  createWord('col3', 'Green', 'verde', 'Cores', 'griin'),
  createWord('col4', 'Yellow', 'amarelo', 'Cores', 'ié-lou'),
  createWord('col5', 'Black', 'preto', 'Cores', 'blék'),
  createWord('col6', 'White', 'branco', 'Cores', 'uait'),
  createWord('col7', 'Brown', 'marrom', 'Cores', 'braun'),
  createWord('col8', 'Gray/Grey', 'cinza', 'Cores', 'grei'),

  // --- EXPANSÃO EXCLUSIVA MÉTODO ITR ---
  
  // ANIMAIS
  createWord('ani1', 'Dog', 'cachorro', 'Animais', 'dóg'),
  createWord('ani2', 'Cat', 'gato', 'Animais', 'két'),
  createWord('ani3', 'Lion', 'leão', 'Animais', 'lái-on'),
  createWord('ani4', 'Tiger', 'tigre', 'Animais', 'tái-guer'),
  createWord('ani5', 'Elephant', 'elefante', 'Animais', 'é-le-fânt'),
  createWord('ani6', 'Monkey', 'macaco', 'Animais', 'mân-qui'),
  createWord('ani7', 'Bird', 'pássaro', 'Animais', 'bêrd'),
  createWord('ani8', 'Snake', 'cobra', 'Animais', 'is-neik'),
  createWord('ani9', 'Shark', 'tubarão', 'Animais', 'chárk'),
  createWord('ani10', 'Horse', 'cavalo', 'Animais', 'rórss'),
  
  // ALIMENTOS
  createWord('fd1', 'Apple', 'maçã', 'Alimentos', 'é-pol'),
  createWord('fd2', 'Banana', 'banana', 'Alimentos', 'ba-né-na'),
  createWord('fd3', 'Bread', 'pão', 'Alimentos', 'bré-dd'),
  createWord('fd4', 'Rice', 'arroz', 'Alimentos', 'raiss'),
  createWord('fd5', 'Meat', 'carne', 'Alimentos', 'miit'),
  createWord('fd6', 'Milk', 'leite', 'Alimentos', 'mí-ol-k'),
  createWord('fd7', 'Egg', 'ovo', 'Alimentos', 'é-gg'),
  createWord('fd8', 'Cheese', 'queijo', 'Alimentos', 'tchiiz'),
  createWord('fd9', 'Fruit', 'fruta', 'Alimentos', 'fruut'),
  createWord('fd10', 'Vegetable', 'vegetal', 'Alimentos', 'vé-dge-ta-bol'),
  
  // SENTIMENTOS EXTRAS
  createWord('emo1', 'Brave', 'corajoso/a', 'Sentimentos', 'breiv'),
  createWord('emo2', 'Calm', 'calmo/a', 'Sentimentos', 'kám'),
  createWord('emo3', 'Proud', 'orgulhoso/a', 'Sentimentos', 'praud'),
  createWord('emo4', 'Confused', 'confuso/a', 'Sentimentos', 'con-fiu-zed'),
  createWord('emo5', 'Surprised', 'surpreso/a', 'Sentimentos', 'sêr-prai-zed'),
  createWord('emo6', 'Bored', 'entediado/a', 'Sentimentos', 'bórd'),
  createWord('emo7', 'Lonely', 'solitário/a', 'Sentimentos', 'loun-li'),
  createWord('emo8', 'Nervous', 'nervoso/a', 'Sentimentos', 'nêr-vass'),
  
  // CASA / CONSTRUÇÃO
  createWord('hou1', 'Garden', 'jardim', 'Casa', 'gár-den'),
  createWord('hou2', 'Roof', 'telhado', 'Casa', 'ruuf'),
  createWord('hou3', 'Wall', 'parede', 'Casa', 'uól'),
  createWord('hou4', 'Floor', 'chão/piso', 'Casa', 'flór'),
  createWord('hou5', 'Ceiling', 'teto', 'Casa', 'sí-lin'),
  createWord('hou6', 'Stairs', 'escadas', 'Casa', 'is-térs'),
  createWord('hou7', 'Garage', 'garagem', 'Casa', 'ga-rá-dge'),
  createWord('hou8', 'Balcony', 'sacada', 'Casa', 'bál-co-ni'),
  
  // ESPORTES / LAZER
  createWord('spo1', 'Soccer', 'futebol', 'Esportes', 'só-ker'),
  createWord('spo2', 'Basketball', 'basquete', 'Esportes', 'bás-ket-ból'),
  createWord('spo3', 'Swimming', 'natação', 'Esportes', 'suí-min'),
  createWord('spo4', 'Running', 'corrida', 'Esportes', 'râ-nin'),
  createWord('spo5', 'Cycling', 'ciclismo', 'Esportes', 'sái-clin'),
  createWord('spo6', 'Game', 'jogo', 'Esportes', 'gueim'),
  createWord('spo7', 'Toy', 'brinquedo', 'Esportes', 'tói'),
  createWord('spo8', 'Holiday', 'feriado', 'Esportes', 'ró-li-dei'),
  
  // NATUREZA EXTRAS
  createWord('nt16', 'Mountain', 'montanha', 'Natureza', 'máun-ten'),
  createWord('nt17', 'Valley', 'vale', 'Natureza', 'vé-li'),
  createWord('nt18', 'Island', 'ilha', 'Natureza', 'ái-lând'),
  createWord('nt19', 'Volcano', 'vulcão', 'Natureza', 'vol-kei-nou'),
  createWord('nt20', 'Desert', 'deserto', 'Natureza', 'dé-zêrt'),
  createWord('nt21', 'Rainbow', 'arco-íris', 'Natureza', 'rein-bou'),
  createWord('nt22', 'Thunder', 'trovão', 'Natureza', 'dân-der'),
  createWord('nt23', 'Lightning', 'relâmpago', 'Natureza', 'lait-nin'),
  createWord('nt24', 'Storm', 'tempestade', 'Natureza', 'is-tórm'),
  createWord('nt25', 'Star', 'estrela', 'Natureza', 'is-tár'),
  
  // PROFISSÕES
  createWord('job1', 'Engineer', 'engenheiro/a', 'Profissões', 'ên-dji-ní-er'),
  createWord('job2', 'Architect', 'arquiteto/a', 'Profissões', 'ár-qui-tét'),
  createWord('job3', 'Photographer', 'fotógrafo/a', 'Profissões', 'fo-tó-gra-fer'),
  createWord('job4', 'Artist', 'artista', 'Profissões', 'ár-tist'),
  createWord('job5', 'Pilot', 'piloto', 'Profissões', 'pái-lot'),
  createWord('job6', 'Driver', 'motorista', 'Profissões', 'drái-ver'),
  createWord('job7', 'Cook/Chef', 'cozinheiro/a', 'Profissões', 'cúk / chéf'),
  createWord('job8', 'Waiter', 'garçom', 'Profissões', 'uei-ter'),
  createWord('job9', 'Salesman', 'vendedor', 'Profissões', 'seils-man'),
  createWord('job10', 'Farmer', 'fazendeiro/a', 'Profissões', 'fár-mer'),
  
  // ESPAÇO / CIÊNCIA
  createWord('sci1', 'Planet', 'planeta', 'Espaço', 'plén-et'),
  createWord('sci2', 'Galaxy', 'galáxia', 'Espaço', 'gá-la-ksi'),
  createWord('sci3', 'Astronaut', 'astronauta', 'Espaço', 'ás-tro-nót'),
  createWord('sci4', 'Rocket', 'foguete', 'Espaço', 'ró-ket'),
  createWord('sci5', 'Telescope', 'telescópio', 'Espaço', 'té-les-coup'),
  createWord('sci6', 'Gravity', 'gravidade', 'Espaço', 'grá-vi-ti'),
  createWord('sci7', 'Oxygen', 'oxigênio', 'Espaço', 'ó-ksi-djen'),
  createWord('sci8', 'Energy', 'energia', 'Espaço', 'é-ner-dji'),
  
  // DIVERSOS
  createWord('mix1', 'Gift', 'presente', 'Geral', 'guift'),
  createWord('mix2', 'Party', 'festa', 'Geral', 'pár-ti'),
  createWord('mix3', 'Secret', 'segredo', 'Geral', 'sí-cret'),
  createWord('mix4', 'Tool', 'ferramenta', 'Geral', 'tuul'),
  createWord('mix5', 'Machine', 'máquina', 'Geral', 'ma-chiín'),
  createWord('mix6', 'Rule', 'regra', 'Geral', 'ru-ol'),
  createWord('mix7', 'System', 'sistema', 'Geral', 'is-tis-têm'),
  createWord('mix8', 'Power', 'poder', 'Geral', 'pau-er'),
  createWord('mix9', 'Success', 'sucesso', 'Geral', 'sâk-sséss'),
  createWord('mix10', 'Failure', 'falha', 'Geral', 'fei-liur'),
  createWord('mix11', 'Mirror', 'espelho', 'Geral', 'mi-ror'), // Repete mas seen tratará
  createWord('mix12', 'Shadow', 'sombra', 'Geral', 'chá-dou'),
  createWord('mix13', 'Light', 'luz', 'Geral', 'lait'),
  createWord('mix14', 'Voice', 'voz', 'Geral', 'vóiss'),
  createWord('mix15', 'Sound', 'som', 'Geral', 'saund'),

  // --- MOBÍLIA ---
  createWord('fur1', 'Desk', 'escrivaninha', 'Mobília', 'désk'),
  createWord('fur2', 'Shelf', 'prateleira', 'Mobília', 'chélf'),
  createWord('fur3', 'Drawer', 'gaveta', 'Mobília', 'dró-er'),
  createWord('fur4', 'Bench', 'banco', 'Mobília', 'bêntch'),
  createWord('fur5', 'Stool', 'banqueta', 'Mobília', 'is-tuul'),
  createWord('fur6', 'Cabinet', 'armário', 'Mobília', 'ké-bi-net'),
  
  // --- FERRAMENTAS ---
  createWord('tol1', 'Hammer', 'martelo', 'Ferramentas', 'ré-mer'),
  createWord('tol2', 'Saw', 'serra', 'Ferramentas', 'só'),
  createWord('tol3', 'Screwdriver', 'chave de fenda', 'Ferramentas', 'is-cru-drai-ver'),
  createWord('tol4', 'Drill', 'furadeira', 'Ferramentas', 'drí-ol'),
  createWord('tol5', 'Nails', 'pregos', 'Ferramentas', 'neils'),
  createWord('tol6', 'Pliers', 'alicate', 'Ferramentas', 'plái-ers'),
  
  // --- VESTUÁRIO ---
  createWord('clo1', 'Belt', 'cinto', 'Vestuário', 'bélt'),
  createWord('clo2', 'Tie', 'gravata', 'Vestuário', 'tái'),
  createWord('clo3', 'Scarf', 'cachecol', 'Vestuário', 'iscárf'),
  createWord('clo4', 'Gloves', 'luvas', 'Vestuário', 'glâvs'),
  createWord('clo5', 'Boots', 'botas', 'Vestuário', 'buuts'),
  createWord('clo6', 'Sandals', 'sandálias', 'Vestuário', 'sén-dals'),
  
  // --- INSTRUMENTOS ---
  createWord('mus1', 'Guitar', 'violão/guitarra', 'Música', 'gui-tár'),
  createWord('mus2', 'Piano', 'piano', 'Música', 'pi-é-nou'),
  createWord('mus3', 'Drums', 'bateria', 'Música', 'drâms'),
  createWord('mus4', 'Violin', 'violino', 'Música', 'vái-o-lin'),
  createWord('mus5', 'Flute', 'flauta', 'Música', 'fluut'),
  createWord('mus6', 'Trumpet', 'trompete', 'Música', 'trâm-pet'),
  
  // --- ESCRITÓRIO ---
  createWord('off1', 'Paper', 'papel', 'Escritório', 'pei-per'),
  createWord('off2', 'Clip', 'clipe', 'Escritório', 'clíp'),
  createWord('off3', 'Stapler', 'grampeador', 'Escritório', 'is-tei-pler'),
  createWord('off4', 'Folder', 'pasta', 'Escritório', 'foul-der'),
  createWord('off5', 'Stamp', 'carimbo', 'Escritório', 'istémp'),
  createWord('off6', 'Eraser', 'borracha', 'Escritório', 'i-rei-zer'),

  // --- FRUTAS / VEGETAIS ---
  createWord('fd11', 'Strawberry', 'morango', 'Alimentos', 'istró-be-ri'),
  createWord('fd12', 'Grape', 'uva', 'Alimentos', 'greip'),
  createWord('fd13', 'Watermelon', 'melancia', 'Alimentos', 'uó-ter-mé-lon'),
  createWord('fd14', 'Pineapple', 'abacaxi', 'Alimentos', 'pái-né-pol'),
  createWord('fd15', 'Lemon', 'limão', 'Alimentos', 'lé-mon'),
  createWord('fd16', 'Potato', 'batata', 'Alimentos', 'po-tei-tou'),
  createWord('fd17', 'Tomato', 'tomate', 'Alimentos', 'to-mei-tou'),
  createWord('fd18', 'Onion', 'cebola', 'Alimentos', 'ó-ni-on'),
  createWord('fd19', 'Garlic', 'alho', 'Alimentos', 'gár-lic'),
  createWord('fd20', 'Carrot', 'cenoura', 'Alimentos', 'ké-rot')
];

// De-duplicate (some words repeat across categories)
const seen = new Set();

// SPRINT 1 & 2 EXCLUSION (Ensures no repetition between manual and automatic sprints)
[
  'PHONE', 'KEYS', 'WALLET', 'BAG', 'PEN', 'PENCIL', 'NOTEBOOK', 'BOOK', 'GLASSES', 'WATCH', 
  'COMPUTER', 'LAPTOP', 'MOUSE', 'KEYBOARD', 'SCREEN', 'CHAIR', 'TABLE', 'LAMP', 'CUP', 'GLASS', 
  'PLATE', 'FORK', 'KNIFE', 'SPOON', 'BOWL', 'PAN', 'FRYING PAN', 'MICROWAVE', 'REFRIGERATOR', 
  'STOVE', 'OVEN', 'DISHWASHER', 'SINK', 'SOAP', 'TOWEL', 'TOOTHBRUSH', 'TOOTHPASTE', 'SHAMPOO', 
  'CONDITIONER', 'HAIR DRYER', 'BRUSH', 'COMB', 'MIRROR', 'BED', 'PILLOW', 'BLANKET', 'SHEET', 
  'WARDROBE', 'CLOSET', 'DOOR', 'WINDOW', 'CURTAIN', 'CARPET', 'RUG', 'SOFA', 'ARMCHAIR', 
  'COFFEE TABLE', 'REMOTE CONTROL', 'TELEVISION', 'SPEAKER', 'HEADPHONES', 'CHARGER', 'BATTERY', 
  'LIGHT BULB', 'FAN', 'AIR CONDITIONER', 'TRASH CAN', 'BROOM', 'DUSTPAN', 'VACUUM CLEANER', 
  'CLOTHES', 'SHIRT', 'PANTS', 'DRESS', 'SKIRT', 'SHOES', 'SOCKS', 'HAT', 'CAP', 'JACKET', 
  'COAT', 'UMBRELLA', 'BACKPACK', 'SUITCASE', 'SCISSORS', 'GLUE', 'TAPE', 'CALCULATOR', 'CLOCK', 
  'CALENDAR', 'NEWSPAPER', 'MAGAZINE', 'ENVELOPE', 'COIN', 'CASH', 'CREDIT CARD', 'ID CARD', 
  'PASSPORT', 'PICTURE FRAME', 'VASE', 'MASTERY', 'FOCUS', 'REFLEX', 'PERFORMANCE'
].forEach(word => seen.add(word.toLowerCase().trim()));

const UNIQUE_POOL = RAW_POOL.filter(w => {
  const normalized = w.en.toLowerCase().trim();
  if (seen.has(normalized)) return false;
  seen.add(normalized);
  return true;
});

export const VOCABULARY_SPRINTS: EssentialWord[] = [
  // SPRINT 1: Objetos (1-50)
  { id: 'obj-1', en: 'PHONE', phonetic: 'foun', pt: 'Telefone', category: 'Objetos', sprint: 1 },
  { id: 'obj-2', en: 'KEYS', phonetic: 'kiis', pt: 'Chaves', category: 'Objetos', sprint: 1 },
  { id: 'obj-3', en: 'WALLET', phonetic: 'uo-lêt', pt: 'Carteira', category: 'Objetos', sprint: 1 },
  { id: 'obj-4', en: 'BAG', phonetic: 'bég', pt: 'Bolsa/Sacola', category: 'Objetos', sprint: 1 },
  { id: 'obj-5', en: 'PEN', phonetic: 'pén', pt: 'Caneta', category: 'Objetos', sprint: 1 },
  { id: 'obj-6', en: 'PENCIL', phonetic: 'pên-ssil', pt: 'Lápis', category: 'Objetos', sprint: 1 },
  { id: 'obj-7', en: 'NOTEBOOK', phonetic: 'nou-t-buk', pt: 'Caderno', category: 'Objetos', sprint: 1 },
  { id: 'obj-8', en: 'BOOK', phonetic: 'buk', pt: 'Livro', category: 'Objetos', sprint: 1 },
  { id: 'obj-9', en: 'GLASSES', phonetic: 'glá-sês', pt: 'Óculos', category: 'Objetos', sprint: 1 },
  { id: 'obj-10', en: 'WATCH', phonetic: 'uo-tch', pt: 'Relógio', category: 'Objetos', sprint: 1 },
  { id: 'obj-11', en: 'COMPUTER', phonetic: 'com-piu-ter', pt: 'Computador', category: 'Objetos', sprint: 1 },
  { id: 'obj-12', en: 'LAPTOP', phonetic: 'lap-top', pt: 'Notebook', category: 'Objetos', sprint: 1 },
  { id: 'obj-13', en: 'MOUSE', phonetic: 'mau-ss', pt: 'Mouse', category: 'Objetos', sprint: 1 },
  { id: 'obj-14', en: 'KEYBOARD', phonetic: 'kii-bord', pt: 'Teclado', category: 'Objetos', sprint: 1 },
  { id: 'obj-15', en: 'SCREEN', phonetic: 'skriin', pt: 'Tela', category: 'Objetos', sprint: 1 },
  { id: 'obj-16', en: 'CHAIR', phonetic: 'tché-âr', pt: 'Cadeira', category: 'Objetos', sprint: 1 },
  { id: 'obj-17', en: 'TABLE', phonetic: 'tei-bol', pt: 'Mesa', category: 'Objetos', sprint: 1 },
  { id: 'obj-18', en: 'LAMP', phonetic: ' lâmp', pt: 'Lâmpada', category: 'Objetos', sprint: 1 },
  { id: 'obj-19', en: 'CUP', phonetic: 'cap', pt: 'Xícara/Copo', category: 'Objetos', sprint: 1 },
  { id: 'obj-20', en: 'GLASS', phonetic: 'glâss', pt: 'Copo (de vidro)', category: 'Objetos', sprint: 1 },
  { id: 'obj-21', en: 'PLATE', phonetic: 'pleit', pt: 'Prato', category: 'Objetos', sprint: 1 },
  { id: 'obj-22', en: 'FORK', phonetic: 'fork', pt: 'Garfo', category: 'Objetos', sprint: 1 },
  { id: 'obj-23', en: 'KNIFE', phonetic: 'nâif', pt: 'Faca', category: 'Objetos', sprint: 1 },
  { id: 'obj-24', en: 'SPOON', phonetic: 'spuun', pt: 'Colher', category: 'Objetos', sprint: 1 },
  { id: 'obj-25', en: 'BOWL', phonetic: 'bou', pt: 'Tigela', category: 'Objetos', sprint: 1 },
  { id: 'obj-26', en: 'PAN', phonetic: 'pan', pt: 'Panela', category: 'Objetos', sprint: 1 },
  { id: 'obj-27', en: 'FRYING PAN', phonetic: 'frái-ing pan', pt: 'Frigideira', category: 'Objetos', sprint: 1 },
  { id: 'obj-28', en: 'MICROWAVE', phonetic: 'mái-cro-ueiv', pt: 'Micro-ondas', category: 'Objetos', sprint: 1 },
  { id: 'obj-29', en: 'REFRIGERATOR', phonetic: 're-fri-ge-rei-tor', pt: 'Geladeira', category: 'Objetos', sprint: 1 },
  { id: 'obj-30', en: 'STOVE', phonetic: 'stouv', pt: 'Fogão', category: 'Objetos', sprint: 1 },
  { id: 'obj-31', en: 'OVEN', phonetic: 'ó-vên', pt: 'Forno', category: 'Objetos', sprint: 1 },
  { id: 'obj-32', en: 'DISHWASHER', phonetic: 'dich-uo-cher', pt: 'Lava-louças', category: 'Objetos', sprint: 1 },
  { id: 'obj-33', en: 'SINK', phonetic: 'sink', pt: 'Pia', category: 'Objetos', sprint: 1 },
  { id: 'obj-34', en: 'SOAP', phonetic: 'sou-p', pt: 'Sabonete', category: 'Objetos', sprint: 1 },
  { id: 'obj-35', en: 'TOWEL', phonetic: 'tau-el', pt: 'Toalha', category: 'Objetos', sprint: 1 },
  { id: 'obj-36', en: 'TOOTHBRUSH', phonetic: 'tuuth-brach', pt: 'Escova de dentes', category: 'Objetos', sprint: 1 },
  { id: 'obj-37', en: 'TOOTHPASTE', phonetic: 'tuuth-peist', pt: 'Pasta de dente', category: 'Objetos', sprint: 1 },
  { id: 'obj-38', en: 'SHAMPOO', phonetic: 'cham-puu', pt: 'Shampoo', category: 'Objetos', sprint: 1 },
  { id: 'obj-39', en: 'CONDITIONER', phonetic: 'con-di-cho-ner', pt: 'Condicionador', category: 'Objetos', sprint: 1 },
  { id: 'obj-40', en: 'HAIR DRYER', phonetic: 'rér drái-er', pt: 'Secador de cabelo', category: 'Objetos', sprint: 1 },
  { id: 'obj-41', en: 'BRUSH', phonetic: 'brach', pt: 'Escova', category: 'Objetos', sprint: 1 },
  { id: 'obj-42', en: 'COMB', phonetic: 'coum', pt: 'Pente', category: 'Objetos', sprint: 1 },
  { id: 'obj-43', en: 'MIRROR', phonetic: 'mi-ror', pt: 'Espelho', category: 'Objetos', sprint: 1 },
  { id: 'obj-44', en: 'BED', phonetic: 'béd', pt: 'Cama', category: 'Objetos', sprint: 1 },
  { id: 'obj-45', en: 'PILLOW', phonetic: 'pi-lou', pt: 'Travesseiro', category: 'Objetos', sprint: 1 },
  { id: 'obj-46', en: 'BLANKET', phonetic: 'blân-kêt', pt: 'Cobertor', category: 'Objetos', sprint: 1 },
  { id: 'obj-47', en: 'SHEET', phonetic: 'chiit', pt: 'Lençol', category: 'Objetos', sprint: 1 },
  { id: 'obj-48', en: 'WARDROBE', phonetic: 'uar-droub', pt: 'Guarda-roupa', category: 'Objetos', sprint: 1 },
  { id: 'obj-49', en: 'CLOSET', phonetic: 'cló-zet', pt: 'Armário (embutido)', category: 'Objetos', sprint: 1 },
  { id: 'obj-50', en: 'DOOR', phonetic: 'dor', pt: 'Porta', category: 'Objetos', sprint: 1 },

  // SPRINT 2: Objetos (51-100)
  { id: 'obj-51', en: 'WINDOW', phonetic: 'uin-dou', pt: 'Janela', category: 'Objetos', sprint: 2 },
  { id: 'obj-52', en: 'CURTAIN', phonetic: 'kãr-tin', pt: 'Cortina', category: 'Objetos', sprint: 2 },
  { id: 'obj-53', en: 'CARPET', phonetic: 'car-pêt', pt: 'Carpete', category: 'Objetos', sprint: 2 },
  { id: 'obj-54', en: 'RUG', phonetic: 'râg', pt: 'Tapete', category: 'Objetos', sprint: 2 },
  { id: 'obj-55', en: 'SOFA', phonetic: 'sou-fa', pt: 'Sofá', category: 'Objetos', sprint: 2 },
  { id: 'obj-56', en: 'ARMCHAIR', phonetic: 'arm-tché-âr', pt: 'Poltrona', category: 'Objetos', sprint: 2 },
  { id: 'obj-57', en: 'COFFEE TABLE', phonetic: 'có-fi tei-bol', pt: 'Mesa de centro', category: 'Objetos', sprint: 2 },
  { id: 'obj-58', en: 'REMOTE CONTROL', phonetic: 're-mout con-trol', pt: 'Controle remoto', category: 'Objetos', sprint: 2 },
  { id: 'obj-59', en: 'TELEVISION', phonetic: 'te-le-vi-jion', pt: 'Televisão', category: 'Objetos', sprint: 2 },
  { id: 'obj-60', en: 'SPEAKER', phonetic: 'spii-ker', pt: 'Caixa de som', category: 'Objetos', sprint: 2 },
  { id: 'obj-61', en: 'HEADPHONES', phonetic: 'réd-founs', pt: 'Fones de ouvido', category: 'Objetos', sprint: 2 },
  { id: 'obj-62', en: 'CHARGER', phonetic: 'tchar-jer', pt: 'Carregador', category: 'Objetos', sprint: 2 },
  { id: 'obj-63', en: 'BATTERY', phonetic: 'ba-te-ri', pt: 'Bateria', category: 'Objetos', sprint: 2 },
  { id: 'obj-64', en: 'LIGHT BULB', phonetic: 'lait bâlb', pt: 'Lâmpada (a bolha de luz)', category: 'Objetos', sprint: 2 },
  { id: 'obj-65', en: 'FAN', phonetic: 'fân', pt: 'Ventilador', category: 'Objetos', sprint: 2 },
  { id: 'obj-66', en: 'AIR CONDITIONER', phonetic: 'ér con-di-cho-ner', pt: 'Ar condicionado', category: 'Objetos', sprint: 2 },
  { id: 'obj-67', en: 'TRASH CAN', phonetic: 'tré-ch can', pt: 'Lixeira', category: 'Objetos', sprint: 2 },
  { id: 'obj-68', en: 'BROOM', phonetic: 'bruum', pt: 'Vassoura', category: 'Objetos', sprint: 2 },
  { id: 'obj-69', en: 'DUSTPAN', phonetic: 'dâst-pan', pt: 'Pá de lixo', category: 'Objetos', sprint: 2 },
  { id: 'obj-70', en: 'VACUUM CLEANER', phonetic: 'vá-kiu cli-ner', pt: 'Aspirador de pó', category: 'Objetos', sprint: 2 },
  { id: 'obj-71', en: 'CLOTHES', phonetic: 'clou-ths', pt: 'Roupas', category: 'Objetos', sprint: 2 },
  { id: 'obj-72', en: 'SHIRT', phonetic: 'shêrt', pt: 'Camisa', category: 'Objetos', sprint: 2 },
  { id: 'obj-73', en: 'PANTS', phonetic: 'pânts', pt: 'Calça', category: 'Objetos', sprint: 2 },
  { id: 'obj-74', en: 'DRESS', phonetic: 'dréss', pt: 'Vestido', category: 'Objetos', sprint: 2 },
  { id: 'obj-75', en: 'SKIRT', phonetic: 'skêrt', pt: 'Saia', category: 'Objetos', sprint: 2 },
  { id: 'obj-76', en: 'SHOES', phonetic: 'shuus', pt: 'Sapatos', category: 'Objetos', sprint: 2 },
  { id: 'obj-77', en: 'SOCKS', phonetic: 'hokss', pt: 'Meias', category: 'Objetos', sprint: 2 },
  { id: 'obj-78', en: 'HAT', phonetic: 'hât', pt: 'Chapéu', category: 'Objetos', sprint: 2 },
  { id: 'obj-79', en: 'CAP', phonetic: 'câp', pt: 'Boné', category: 'Objetos', sprint: 2 },
  { id: 'obj-80', en: 'JACKET', phonetic: 'djá-kêt', pt: 'Jaqueta', category: 'Objetos', sprint: 2 },
  { id: 'obj-81', en: 'COAT', phonetic: 'cout', pt: 'Casaco', category: 'Objetos', sprint: 2 },
  { id: 'obj-82', en: 'UMBRELLA', phonetic: 'âm-bre-la', pt: 'Guarda-chuva', category: 'Objetos', sprint: 2 },
  { id: 'obj-83', en: 'BACKPACK', phonetic: 'bék-pak', pt: 'Mochila', category: 'Objetos', sprint: 2 },
  { id: 'obj-84', en: 'SUITCASE', phonetic: 'suut-keis', pt: 'Mala de viagem', category: 'Objetos', sprint: 2 },
  { id: 'obj-85', en: 'SCISSORS', phonetic: 'ssi-zors', pt: 'Tesoura', category: 'Objetos', sprint: 2 },
  { id: 'obj-86', en: 'GLUE', phonetic: 'glu', pt: 'Cola', category: 'Objetos', sprint: 2 },
  { id: 'obj-87', en: 'TAPE', phonetic: 'teip', pt: 'Fita adesiva', category: 'Objetos', sprint: 2 },
  { id: 'obj-88', en: 'CALCULATOR', phonetic: 'cal-kiu-lei-tor', pt: 'Calculadora', category: 'Objetos', sprint: 2 },
  { id: 'obj-89', en: 'CLOCK', phonetic: 'clok', pt: 'Relógio (de parede)', category: 'Objetos', sprint: 2 },
  { id: 'obj-90', en: 'CALENDAR', phonetic: 'ca-len-der', pt: 'Calendário', category: 'Objetos', sprint: 2 },
  { id: 'obj-91', en: 'NEWSPAPER', phonetic: 'niu-ss-pei-per', pt: 'Jornal', category: 'Objetos', sprint: 2 },
  { id: 'obj-92', en: 'MAGAZINE', phonetic: 'há-ga-ziin', pt: 'Revista', category: 'Objetos', sprint: 2 },
  { id: 'obj-93', en: 'ENVELOPE', phonetic: 'én-ve-loup', pt: 'Envelope', category: 'Objetos', sprint: 2 },
  { id: 'obj-94', en: 'COIN', phonetic: 'coin', pt: 'Moeda', category: 'Objetos', sprint: 2 },
  { id: 'obj-95', en: 'CASH', phonetic: 'câch', pt: 'Dinheiro em espécie', category: 'Objetos', sprint: 2 },
  { id: 'obj-96', en: 'CREDIT CARD', phonetic: 'cre-dit card', pt: 'Cartão de crédito', category: 'Objetos', sprint: 2 },
  { id: 'obj-97', en: 'ID CARD', phonetic: 'ai-di card', pt: 'Documento de identidade', category: 'Objetos', sprint: 2 },
  { id: 'obj-98', en: 'PASSPORT', phonetic: 'pás-port', pt: 'Passaporte', category: 'Objetos', sprint: 2 },
  { id: 'obj-99', en: 'PICTURE FRAME', phonetic: 'pik-tchur freim', pt: 'Porta-retrato', category: 'Objetos', sprint: 2 },
  { id: 'obj-100', en: 'VASE', phonetic: 'veiz', pt: 'Vaso', category: 'Objetos', sprint: 2 },

  // SPRINT 3-12: Full De-duplicated Vocabulary Pool
  // We have ~500 unique words to distribute across 10 sprints (50/sprint)
  ...UNIQUE_POOL.map((w, i) => ({
    ...w,
    sprint: 3 + Math.floor(i / 50)
  })).filter(w => w.sprint <= 12),

  // Final 4 words to complete 600 (ensuring the target is met if de-duplication reduced the count)
  { id: 'final-1', en: 'Mastery', pt: 'Maestria', phonetic: 'máss-te-ri', category: 'ITR', sprint: 12 },
  { id: 'final-2', en: 'Focus', pt: 'Foco', phonetic: 'fou-cas', category: 'ITR', sprint: 12 },
  { id: 'final-3', en: 'Reflex', pt: 'Reflexo', phonetic: 'ri-fleks', category: 'ITR', sprint: 12 },
  { id: 'final-4', en: 'Performance', pt: 'Alta Performance', phonetic: 'per-for-mance', category: 'ITR', sprint: 12 }
];
